In [63]:
import pandas as pd



### Q1. Pandas version

In [64]:
print(f"Pandas version {pd.__version__}")

Pandas version 2.2.2


### Getting the data

In [65]:
laptops_df=pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

In [66]:
laptops_df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

### Q2. Records count

In [8]:
rec_count = len(laptops_df)
print(f"Number of records in the file: {rec_count}")

Number of records in the file: 2160


### Q3. Laptop brands

In [9]:
laptops_df["Brand"].nunique()

27

### Q4. Missing values

In [10]:
laptops_df.isnull().sum()
#3

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

### Q5. Maximum final price(What's the maximum final price of Dell notebooks in the dataset?)

In [11]:
max_final_price=laptops_df[laptops_df["Brand"]=="Dell"]["Final Price"].max()
print(f"Max final price {max_final_price}")

Max final price 3936.0


### Q6. Median value of Screen

In [12]:
median_value_screen = laptops_df["Screen"].dropna().median()
print(f"Median screen value {median_value_screen}")

Median screen value 15.6


In [73]:
laptops_df.groupby("Screen")["Laptop"].count().sort_values(ascending=False)

#15.60 1009

Screen
15.60    1009
14.00     392
16.00     174
17.30     161
13.30     131
16.10      48
17.00      33
13.00      27
15.00      21
13.50      19
13.40      19
11.60      16
14.20      14
12.30      13
14.10      11
13.60      11
16.20      10
15.30       8
10.50       7
12.40       6
14.40       6
15.40       5
12.00       4
18.00       3
14.50       3
13.90       2
12.50       1
10.10       1
10.95       1
Name: Laptop, dtype: int64

In [74]:
filled_na=laptops_df["Screen"].fillna(15.6)
#Replace column with the filled na values
laptops_df["Screen"] = filled_na

In [75]:
median_value_screen = laptops_df["Screen"].dropna().median()
print(f"Median screen value {median_value_screen}")

Median screen value 15.6


Answer: No

### Q7. Sum of weights

In [76]:
innjoo_df = laptops_df[laptops_df["Brand"]=="Innjoo"]

selected_columns = innjoo_df[["RAM","Storage","Screen"]]

In [77]:
selected_columns.reset_index()

index  RAM  Storage  Screen
0   1478    8      256    15.6
1   1479    8      512    15.6
2   1480    4       64    14.1
3   1481    6       64    14.1
4   1482    6      128    14.1
5   1483    6      128    14.1

In [78]:
X=selected_columns.values

In [83]:
XT=X.T

In [84]:
XT

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [85]:
XTX=XT.dot(X)

In [86]:
import numpy as np

In [93]:
XTX_inv=np.linalg.inv(XTX) #The inverse of XTX
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [89]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [98]:
w=XTX_inv.dot(XT).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [102]:
w.sum()

np.float64(91.2998806299555)